# with react-native >= 0.72
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

# Set the iOS deployment target
platform :ios, podfile_properties['ios.deploymentTarget'] || '16.0'

install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

target 'VolleyballProject' do
  config = use_native_modules!
  if config.nil? || config[:reactNativePath].nil?
    config = { reactNativePath: '../node_modules/react-native' }
  end

  use_frameworks! :linkage => :static

  # Uncomment the permissions you want to use
  setup_permissions([
    'Notifications',
    'Camera',
    'LocationWhenInUse',
  ])

  # Firebase and other pods
  pod 'GoogleUtilities', :modular_headers => true
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'BEMCheckBox'
  pod 'Google-Mobile-Ads-SDK'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'GoogleMaps'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'



  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false'
  )

  post_install do |installer|
    react_native_post_install(installer)

    installer.target_installation_results.pod_target_installation_results.each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      end
    end
  end
end
